version: '3.7'

services:
  api:
    container_name: api
    image: helpshare_api
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
        - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
  postgres:
    restart: always
    container_name: helpshare_postgres
    image: postgres:12-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD:
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
