default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
  host: <%= ENV.fetch('DB_HOST', 'postgres') %>
  port: 5432

development:
  <<: *default
  database: helpshare_api_development

test:
  <<: *default
  database: helpshare_api_test

production:
  <<: *default
  database: helpshare_api_production
