default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV['postgres'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  <<: *default
  database: helpshare_api_development

test:
  <<: *default
  database: helpshare_api_test

production:
  <<: *default
  database: helpshare_api_production
